### ISSUE TITLE
AM/PM

### ISSUE THREAD

**Issue by miguelmartin75** [andreyorst/small-clock#1]
Thanks, I love your breezemite theme and this small clock since KDE's font size is ridiculous. However, for those wanting AM/PM rather than 24hr clocks, simply just change line 26 in `aorst.plasmoid.smallclock/contents/ui/CompactRepresentation.qml` 

    text: Qt.formatDateTime( time_src.data.Local.DateTime, "ddd h:mm" )

to 

    text: Qt.formatDateTime( time_src.data.Local.DateTime, "ddd h:mm ap" )

or replace ap with AP if you'd prefer a capital AM/PM.

**Comment by andreyorst** [comment]
Thanks for the suggestion!
Actually I don't use this plasmoid since i've found [event calendar](https://store.kde.org/p/998901/) plasmoid, which is far better than this one, and i highly recommend you to try it. 
Don't be scared by how it looks by default, you can tweak it a lot. For example this is my config:
![image](https://user-images.githubusercontent.com/19470159/31316182-fbc7f968-ac30-11e7-89d6-c8901e0217e7.png)
